### ISSUE TITLE
Valuta property return EUR/MWh by default

### ISSUE THREAD

**Issue by phuongpham** [Csstenersen/node-red-contrib-nordpool-api#2]
I have used the palette for long time now.
Suddenly the object property valuta return value in EUR/MWh
I have always set this to Currency to NOK/MWh.
I have tried to change to different currency but it seems like it always return as EUR/MWh

Example:

{"Area":"Kr.sand","Timestamp":"2021-02-08 00:00","StartTime":"2021-02-08 00:00","EndTime":"2021-02-08 01:00","Price":40.06,"Valuta":"EUR/MWh"}

![image](https://user-images.githubusercontent.com/2634344/107269366-cb3f1d00-6a49-11eb-8960-396dda23e0e2.png)

**Comment by Csstenersen** [comment]
Hi @phuongpham, and thanks for the feedback. 
It seems like nordpool has changed their sites a little and the query that is used does not contain other than EUR at the moment. I will need to make some change in my node to get this to work properly again. give me a couple of days to get this up and running again.

**Comment by phuongpham** [comment]
> Hi @phuongpham, and thanks for the feedback.
> It seems like nordpool has changed their sites a little and the query that is used does not contain other than EUR at the moment. I will need to make some change in my node to get this to work properly again. give me a couple of days to get this up and running again.

Great! Just let me know if you need some testing

**Comment by Csstenersen** [comment]
@phuongpham now you can upgrade to v3.0.8 and give it a try

**Comment by phuongpham** [comment]
I just tested with the new version and can confirm it working as expected now!
Thanks for your quick help :)

**Comment by hotNipi** [comment]
I see you have disabled many country codes  due the changes at the nordpool side. Do you have any plans to get them back in business at some time? At least for EE  ...

**Comment by Csstenersen** [comment]
@hotNipi that is correct. I don´t have any plans for this settled but i will look this up again when I find the time for it.
