### ISSUE TITLE
[Request for new functionality] Output as common strategy input format?

### ISSUE THREAD

**Issue by houser42** [Csstenersen/node-red-contrib-nordpool-api#4]
Hello,

Have you already or will you consider an option to format the output as "common strategy input format" 
for nodes that require this? As formatted [here](https://power-saver.smoky.no/nodes/strategy-input.html)
Can you comment if this is feasible? Many thanks.

Example snippet from the link:
`{
  "priceData": [
    {
      "value": 0.9544,
      "start": "2021-12-07T00:00:00.000+01:00"
    },
    {
      "value": 0.8973,
      "start": "2021-12-07T01:00:00.000+01:00"
    },
    {
      "value": 0.8668,
      "start": "2021-12-07T02:00:00.000+01:00"
    },
    {
      "value": 0.8683,
      "start": "2021-12-07T03:00:00.000+01:00"
    },
    {
      "value": 0.8942,
      "start": "2021-12-07T04:00:00.000+01:00"
    }
    // ... normally 24 or 48 hours
  ]
}`

**Comment by zinen** [comment]
Havnet heard of "common strategy input format" and googling it don't tell me much. Also your link shows an error 404 page. Do you have some more info about this?

**Comment by houser42** [comment]
Hello,
Sorry about broken link. This was a while ago.
This was solved here for us if you have an interest:
https://github.com/ottopaulsen/node-red-contrib-power-saver/issues/40
Many thanks

**Comment by zinen** [comment]
Ah I see now. The "common strategy input format" reference the desired values of time node-red-contrib-power-saver node expects. Perfect that you got this fixed in https://github.com/ottopaulsen/node-red-contrib-power-saver/issues/40. You can close this issue then.
