### ISSUE TITLE
[Help] example code for function nodes?

### ISSUE THREAD

**Issue by houser42** [Csstenersen/node-red-contrib-nordpool-api#5]
Hello,

Is there some example code for three separate function nodes from the payload of this very useful node to request:
1. price right now
2. highest price during the day
3. lowest  price during the day. 

Would appreciate any hints to get started? Many thanks!

**Comment by Csstenersen** [comment]
Hi  @houser42 and thanks for the response. 
paste the code below into a function node and you will get min, max and now object. 
you will get min and max values from all the 48 hours that are from the output from the node. I will see if I can filter this out to be presented as min/max values for "today" and "tomorrow" later on

`//Declare variables
var now = new Date()
var nowMinusOneHour = new Date().setHours(new Date().getHours() - 1)
var msg1 = {
    payload: {}
} 

//Sort prices from min to max
msg.payload.sort(function (a, b) {
    return a.Price - b.Price
    })

//Convert date string to Date object 
for (var i in msg.payload) {
    msg.payload[i].StartTime = Date.parse(msg.payload[i].StartTime)
}

//find object with current hour
for (var i in msg.payload) {
    if (msg.payload[i].StartTime < now && msg.payload[i].StartTime > nowMinusOneHour){
        msg1.payload.now = msg.payload[i]
    }
}

//write min and max to payload
msg1.payload.min = msg.payload[0],
msg1.payload.max = msg.payload[msg.payload.length - 1]

//Send message
node.send(msg1);`

**Comment by houser42** [comment]
You are a star. Appreciate so much! Works perfectly.. Zillion kudos..

**Comment by Csstenersen** [comment]
@houser42 I have now an updated function that separate today and tomorrow max and min:

`//Declare variables
var now = new Date()
var nowMinusOneHour = new Date().setHours(new Date().getHours() - 1)
var today = new Date().getDate()
var tomorrow = new Date().getDate() + 1
var msg1 = {
    payload: {
        today: [],
        today_max: {},
        today_min: {},
        now: {},
        tomorrow: [],
        tomorrow_max: {},
        tomorrow_min: {}
    }
} 

//split prices for today and tomorrow
for (var i in msg.payload) {
    msg.payload[i].StartTime = new Date(msg.payload[i].StartTime)
    var date = new Date(msg.payload[i].StartTime).getDate()
    if (date == today) {
        msg1.payload.today.push(msg.payload[i])
    }
    else if ((date == tomorrow)) {
        msg1.payload.tomorrow.push(msg.payload[i])
    }
}

//find min and max for today
var a = msg1.payload.today
a.sort(function (a, b) {
    return a.Price - b.Price
})

//write min and max for today
msg1.payload.today_min = a[0],
msg1.payload.today_max = a[a.length - 1]

//find min and max for tomorrow
a = msg1.payload.tomorrow
a.sort(function (a, b) {
    return a.Price - b.Price
})

//write min and max for tomorrow
msg1.payload.tomorrow_min = a[0],
msg1.payload.tomorrow_max = a[a.length - 1]

//find object within current hour
for (var i in msg.payload) {
    if (msg.payload[i].StartTime < now && msg.payload[i].StartTime > nowMinusOneHour){
        msg1.payload.now = msg.payload[i]
    }
}

//Send message
node.send(msg1)`

**Comment by houser42** [comment]
It looks like this code broke today for some reason? I see the pricing in the graph you kindly provided a year ago but not tomorrows high and low prices from this thread. If you are seeing the same can you take a look when you have a moment, if something has changed in the API?
This is the raw output from the node:
`{
	"payload": [{
		"Area": "SE3",
		"Timestamp": "2022-11-30 00:00",
		"StartTime": "2022-11-30 00:00",
		"EndTime": "2022-11-30 01:00",
		"Price": 2924.64,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 01:00",
		"StartTime": "2022-11-30 01:00",
		"EndTime": "2022-11-30 02:00",
		"Price": 2826.99,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 02:00",
		"StartTime": "2022-11-30 02:00",
		"EndTime": "2022-11-30 03:00",
		"Price": 2790.8,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 03:00",
		"StartTime": "2022-11-30 03:00",
		"EndTime": "2022-11-30 04:00",
		"Price": 2774.02,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 04:00",
		"StartTime": "2022-11-30 04:00",
		"EndTime": "2022-11-30 05:00",
		"Price": 2846.71,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 05:00",
		"StartTime": "2022-11-30 05:00",
		"EndTime": "2022-11-30 06:00",
		"Price": 3084.74,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 06:00",
		"StartTime": "2022-11-30 06:00",
		"EndTime": "2022-11-30 07:00",
		"Price": 3621.38,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 07:00",
		"StartTime": "2022-11-30 07:00",
		"EndTime": "2022-11-30 08:00",
		"Price": 4734.67,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 08:00",
		"StartTime": "2022-11-30 08:00",
		"EndTime": "2022-11-30 09:00",
		"Price": 5210.62,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 09:00",
		"StartTime": "2022-11-30 09:00",
		"EndTime": "2022-11-30 10:00",
		"Price": 5216.07,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 10:00",
		"StartTime": "2022-11-30 10:00",
		"EndTime": "2022-11-30 11:00",
		"Price": 5173.67,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 11:00",
		"StartTime": "2022-11-30 11:00",
		"EndTime": "2022-11-30 12:00",
		"Price": 5258.79,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 12:00",
		"StartTime": "2022-11-30 12:00",
		"EndTime": "2022-11-30 13:00",
		"Price": 4904.26,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 13:00",
		"StartTime": "2022-11-30 13:00",
		"EndTime": "2022-11-30 14:00",
		"Price": 4909.49,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 14:00",
		"StartTime": "2022-11-30 14:00",
		"EndTime": "2022-11-30 15:00",
		"Price": 5059.56,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 15:00",
		"StartTime": "2022-11-30 15:00",
		"EndTime": "2022-11-30 16:00",
		"Price": 4999.84,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 16:00",
		"StartTime": "2022-11-30 16:00",
		"EndTime": "2022-11-30 17:00",
		"Price": 5213.89,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 17:00",
		"StartTime": "2022-11-30 17:00",
		"EndTime": "2022-11-30 18:00",
		"Price": 5487.98,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 18:00",
		"StartTime": "2022-11-30 18:00",
		"EndTime": "2022-11-30 19:00",
		"Price": 5396.98,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 19:00",
		"StartTime": "2022-11-30 19:00",
		"EndTime": "2022-11-30 20:00",
		"Price": 5069.37,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 20:00",
		"StartTime": "2022-11-30 20:00",
		"EndTime": "2022-11-30 21:00",
		"Price": 4510.93,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 21:00",
		"StartTime": "2022-11-30 21:00",
		"EndTime": "2022-11-30 22:00",
		"Price": 3751.29,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 22:00",
		"StartTime": "2022-11-30 22:00",
		"EndTime": "2022-11-30 23:00",
		"Price": 3370.39,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-11-30 23:00",
		"StartTime": "2022-11-30 23:00",
		"EndTime": "2022-12-01 00:00",
		"Price": 2894.34,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 00:00",
		"StartTime": "2022-12-01 00:00",
		"EndTime": "2022-12-01 01:00",
		"Price": 3117.62,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 01:00",
		"StartTime": "2022-12-01 01:00",
		"EndTime": "2022-12-01 02:00",
		"Price": 3110.84,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 02:00",
		"StartTime": "2022-12-01 02:00",
		"EndTime": "2022-12-01 03:00",
		"Price": 3039.64,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 03:00",
		"StartTime": "2022-12-01 03:00",
		"EndTime": "2022-12-01 04:00",
		"Price": 2933.44,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 04:00",
		"StartTime": "2022-12-01 04:00",
		"EndTime": "2022-12-01 05:00",
		"Price": 2973.91,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 05:00",
		"StartTime": "2022-12-01 05:00",
		"EndTime": "2022-12-01 06:00",
		"Price": 3100.56,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 06:00",
		"StartTime": "2022-12-01 06:00",
		"EndTime": "2022-12-01 07:00",
		"Price": 3862.77,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 07:00",
		"StartTime": "2022-12-01 07:00",
		"EndTime": "2022-12-01 08:00",
		"Price": 4930.89,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 08:00",
		"StartTime": "2022-12-01 08:00",
		"EndTime": "2022-12-01 09:00",
		"Price": 5067.71,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 09:00",
		"StartTime": "2022-12-01 09:00",
		"EndTime": "2022-12-01 10:00",
		"Price": 5032.6,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 10:00",
		"StartTime": "2022-12-01 10:00",
		"EndTime": "2022-12-01 11:00",
		"Price": 4955.28,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 11:00",
		"StartTime": "2022-12-01 11:00",
		"EndTime": "2022-12-01 12:00",
		"Price": 4882.65,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 12:00",
		"StartTime": "2022-12-01 12:00",
		"EndTime": "2022-12-01 13:00",
		"Price": 4789.14,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 13:00",
		"StartTime": "2022-12-01 13:00",
		"EndTime": "2022-12-01 14:00",
		"Price": 4883.86,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 14:00",
		"StartTime": "2022-12-01 14:00",
		"EndTime": "2022-12-01 15:00",
		"Price": 5075.58,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 15:00",
		"StartTime": "2022-12-01 15:00",
		"EndTime": "2022-12-01 16:00",
		"Price": 5064.98,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 16:00",
		"StartTime": "2022-12-01 16:00",
		"EndTime": "2022-12-01 17:00",
		"Price": 5009.63,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 17:00",
		"StartTime": "2022-12-01 17:00",
		"EndTime": "2022-12-01 18:00",
		"Price": 5294.33,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 18:00",
		"StartTime": "2022-12-01 18:00",
		"EndTime": "2022-12-01 19:00",
		"Price": 5138.14,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 19:00",
		"StartTime": "2022-12-01 19:00",
		"EndTime": "2022-12-01 20:00",
		"Price": 5007.99,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 20:00",
		"StartTime": "2022-12-01 20:00",
		"EndTime": "2022-12-01 21:00",
		"Price": 4711.71,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 21:00",
		"StartTime": "2022-12-01 21:00",
		"EndTime": "2022-12-01 22:00",
		"Price": 4150.52,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 22:00",
		"StartTime": "2022-12-01 22:00",
		"EndTime": "2022-12-01 23:00",
		"Price": 3636.15,
		"Valuta": "SEK/MWh"
	}, {
		"Area": "SE3",
		"Timestamp": "2022-12-01 23:00",
		"StartTime": "2022-12-01 23:00",
		"EndTime": "2022-12-02 00:00",
		"Price": 3250.95,
		"Valuta": "SEK/MWh"
	}],
	"topic": "hourly",
	"_msgid": "0dd5db49139e1e91"
}`

Thisis  the debug response after your function node as of today:
`msg : Object
object
payload: object
today: array[24]
today_max: object
today_min: object
now: object
tomorrow: array[0]
tomorrow_max: undefined
tomorrow_min: undefined
_msgid: "d4de5a106912b0af`

**Comment by Csstenersen** [comment]
Hi again and thanks for the response. 
I found the bug regarding this issue. 

please try pasting this into a function node:

`
//Declare variables
var now = new Date()
var nowMinusOneHour = new Date().setHours(new Date().getHours() - 1)
var today = new Date().getDate()
var tomorrow = new Date()
tomorrow.setDate(tomorrow.getDate() + 1)
var msg1 = {
    payload: {
        today: [],
        today_max: {},
        today_min: {},
        now: {},
        tomorrow: [],
        tomorrow_max: {},
        tomorrow_min: {}
    }
} 

//split prices for today and tomorrow
for (var i in msg.payload) {
    msg.payload[i].StartTime = new Date(msg.payload[i].StartTime)
    var date = new Date(msg.payload[i].StartTime).getDate()
    if (date == today) {
        msg1.payload.today.push(msg.payload[i])
    }
    else if ((date = tomorrow)) {
        msg1.payload.tomorrow.push(msg.payload[i])
    }
}

//find min and max for today
var a = msg1.payload.today
a.sort(function (a, b) {
    return a.Price - b.Price
})

//write min and max for today
msg1.payload.today_min = a[0],
msg1.payload.today_max = a[a.length - 1]

//find min and max for tomorrow
a = msg1.payload.tomorrow
a.sort(function (a, b) {
    return a.Price - b.Price
})

//write min and max for tomorrow
msg1.payload.tomorrow_min = a[0],
msg1.payload.tomorrow_max = a[a.length - 1]

//find object within current hour
for (var i in msg.payload) {
    if (msg.payload[i].StartTime < now && msg.payload[i].StartTime > nowMinusOneHour){
        msg1.payload.now = msg.payload[i]
    }
}

//Send message
node.send(msg1)
`

**Comment by houser42** [comment]
Yes, that fixed it. You're a star! ;)
