### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by SuperJERK22** [Csstenersen/node-red-contrib-nordpool-api#6]
The correct url is https://www.nordpoolgroup.com/api/marketdata/page/10?currency=,EUR,EUR,EUR&endDate=09-10-2024

The old url https://www.nordpoolspot.com/api/marketdata/page/10?currency=,EUR,EUR,EUR&endDate=09-10-2024 is not working anymore. 

Can you fix this? Thanks!

**Comment by Amli2011** [comment]
The two urls in the last post gave me 404 and 503.
There is a new api, not only a new url. 

https://dataportal-api.nordpoolgroup.com/api/DayAheadPrices?date=2024-10-16&market=DayAhead&deliveryArea=NO3&currency=NOK

**Comment by Csstenersen** [comment]
Tanks for the issue report. 
I will have a look at this as soon as I find time.

**Comment by OverWorldD** [comment]
Hi! Yeah my price adjustment code stopped working and i realize i'm getting "Error: Prices not available when requesting https://www.nordpoolgroup.com/api/marketdata/page/35?currency=,EUR&endDate=18-10-2024"

**Comment by Csstenersen** [comment]
This is not maintained. Have a look at this node that i think does the same job: https://github.com/zinen/node-red-contrib-nordpool-api-plus
