### ISSUE TITLE
"Node tried to send a message of type string" error

### ISSUE THREAD

**Issue by phuongpham** [Csstenersen/node-red-contrib-nordpool-api#7]
Starting from 15. october I'm getting follow error when running the pallet

"Node tried to send a message of type string"

**Comment by houser42** [comment]
Seeing the same. Assume something has changed. Grateful for acumen so we know if this node is still maintained. Many thanks.

**Comment by Csstenersen** [comment]
This is not maintaines. Have a look at this node that i think does the same job: https://github.com/zinen/node-red-contrib-nordpool-api-plus
